---

- name: "Directory should be created with correct ownership and privileges"
  file:
    path: "/etc/graylog/server"
    owner: "graylog"
    group: "graylog"
    mode: 0750

- debug: var=item.mount
  with_items: "{{ ansible_mounts }}"
  tags: journal-message-size

- name: GET disk size to limit journal size
  set_fact:
    graylog_message_journal_max_size: "{{ (item.size_total / 1024 / 1024 / 1024 * 0.9)|int }}gb"
  when: "graylog_message_journal_max_size == '0gb' and item.mount == data_disk"
  with_items: "{{ ansible_mounts }}"
  tags: journal-message-size

- debug: var=graylog_message_journal_max_size
  tags: journal-message-size

- name: "Graylog server should be configured"
  template:
    src: "graylog.server.conf.j2"
    dest: "/etc/graylog/server/server.conf"
    owner: "graylog"
    group: "graylog"
    mode: 0644
  notify: "restart graylog-server"

- name: "Graylog server defaults should be configured"
  template:
    src: "graylog.server.default.j2"
    dest: "{{ graylog_server_defaults_file_path }}"
    owner: "graylog"
    group: "graylog"
    mode: 0644
  notify: "restart graylog-server"

- name: "Graylog server should start after reboot"
  file:
    path: "/etc/init/graylog-server.override"
    state: "absent"

- meta: "flush_handlers"

- name: "Wait for Graylog server to startup"
  uri:
    url: "{{ graylog_http_publish_uri }}"
    status_code: 200
    validate_certs: False
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  when: graylog_not_testing
